export type ClinicClassification =
  | "target_candidate"
  | "verified_operator"
  | "competitor_benchmark";

export type CountyName =
  | "Harris County"
  | "Bexar County"
  | "Tarrant County"
  | "Dallas County"
  | "Travis County"
  | "Collin County";

export type MetroId = "houston" | "dfw" | "san-antonio" | "austin";

export type OwnershipStatus =
  | "founder_named"
  | "clinician_owned_named"
  | "independent_unnamed"
  | "platform_scaled"
  | "nonprofit"
  | "hospital_system"
  | "sponsor_platform";

export type WorkflowState = "identified" | "verified" | "target" | "outreach" | "passed";

export type SourceLink = { label: string; url: string };

export type SosCheck = {
  status: "sos_named" | "npi_named" | "site_named" | "not_pulled" | "not_found";
  legalName: string | null;
  members: string | null;
  checkedOn: string;
  note: string;
};

export type LicenseCheck = {
  board: "TDLR" | "ECPTOTE";
  status: "found" | "not_found" | "not_pulled";
  licenseNumber: string | null;
  holderName: string | null;
  checkedOn: string;
  note: string;
};

export const CHECKED_ON = "2026-09-01";

export function licensesNotPulled(...boards: Array<LicenseCheck["board"]>): LicenseCheck[] {
  return boards.map((board) => ({
    board,
    status: "not_pulled" as const,
    licenseNumber: null,
    holderName: null,
    checkedOn: CHECKED_ON,
    note: "Interactive board search not completed in this pass. Lookup link is the next step. Do not read this as unlicensed.",
  }));
}

export function sosNamed(args: {
  status: SosCheck["status"];
  legalName: string | null;
  members: string | null;
  note: string;
}): SosCheck {
  return { ...args, checkedOn: CHECKED_ON };
}

export type VerifiedClinic = {
  id: string;
  countyName: CountyName;
  metroId: MetroId;
  name: string;
  legalName: string | null;
  websiteUrl: string;
  sourceUrl: string;
  sources: SourceLink[];
  services: Array<"SLP" | "OT" | "PT" | "ABA" | "feeding">;
  footprint: string;
  locationCount: number;
  clinicianEstimate: string;
  ownershipSignal: string;
  ownershipStatus: OwnershipStatus;
  ownerName: string | null;
  peSignal: string;
  classification: ClinicClassification;
  verificationNote: string;
  nextAction: string;
  licenseLookups: SourceLink[];
  sosCheck: SosCheck;
  licenseChecks: LicenseCheck[];
  city: string;
  lat: number;
  lng: number;
  outreachRank: number | null;
  verifiedAt: "2026-09-01";
  defaultWorkflow: WorkflowState;
};

export type RejectedRecord = {
  id: string;
  name: string;
  market: string;
  category:
    | "scaled_platform"
    | "nonprofit"
    | "hospital"
    | "closed"
    | "not_a_clinic"
    | "home_health"
    | "not_acquireable_entity"
    | "sponsor_own_clinics";
  reason: string;
  sourceUrl?: string;
};

const TDLR: SourceLink = {
  label: "TDLR SLP license search",
  url: "https://www.tdlr.texas.gov/LicenseSearch/",
};
const ECPTOTE: SourceLink = {
  label: "ECPTOTE OT/PT license lookup",
  url: "https://ptot.texas.gov/page/look-up-a-license",
};
const SOS: SourceLink = {
  label: "Texas SOS entity search",
  url: "https://mycpa.cpa.state.tx.us/coa/",
};

export const VERIFIED_CLINICS: VerifiedClinic[] = [
  {
    id: "therapedia",
    countyName: "Tarrant County",
    metroId: "dfw",
    name: "Therapedia, LLC",
    legalName: "Therapedia, LLC",
    websiteUrl: "https://www.therapediacenter.com/",
    sourceUrl: "https://www.therapediacenter.com/",
    sources: [
      { label: "Practice site (owner named)", url: "https://www.therapediacenter.com/" },
      { label: "Debra Kitchens LinkedIn", url: "https://www.linkedin.com/in/debra-kitchens-pt-4aa07a28" },
    ],
    services: ["SLP", "OT", "PT"],
    footprint: "Keller + Justin",
    locationCount: 2,
    clinicianEstimate: "19 on LinkedIn company page; RocketReach 23 — directory estimates, not filings",
    ownershipSignal: "Debra Kitchens, PT — founder/CEO since 2004. Site and LinkedIn both name her as owner. Self-owned on LinkedIn.",
    ownershipStatus: "founder_named",
    ownerName: "Debra Kitchens, PT",
    peSignal: "No PE or recap press found. Treat as founder-held until SOS confirms members.",
    classification: "target_candidate",
    verificationNote: "Best-documented Tarrant independent. Multidisciplinary, two sites, named PT owner, 20+ years.",
    nextAction: "Pull SOS members. Call Kitchens. This is first outreach in Tarrant.",
    licenseLookups: [ECPTOTE, TDLR, SOS],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: "Therapedia, LLC",
      members: "Debra Kitchens, PT (site + LinkedIn). SOS members not pulled.",
      note: "Named founder/CEO on the practice site. Texas SOS filing not pulled.",
    }),
    licenseChecks: licensesNotPulled("ECPTOTE", "TDLR"),
    city: "Keller",
    lat: 32.9346,
    lng: -97.2517,
    outreachRank: 1,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "target",
  },
  {
    id: "frisco-feeding",
    countyName: "Collin County",
    metroId: "dfw",
    name: "Frisco Feeding & Speech Therapy",
    legalName: null,
    websiteUrl: "https://friscofeedingslp.com/",
    sourceUrl: "https://friscofeedingslp.com/",
    sources: [
      { label: "Four clinic addresses", url: "https://friscofeedingslp.com/" },
      { label: "Voyage Dallas founder interview", url: "https://voyagedallas.com/interview/meet-jeanine-roddy-frisco-feeding-speech-therapy-frisco-tx/" },
    ],
    services: ["SLP", "OT", "feeding"],
    footprint: "Frisco, McKinney, Prosper, Melissa",
    locationCount: 4,
    clinicianEstimate: "LinkedIn 22 employees (+29% YoY) — directory estimate",
    ownershipSignal: "Jeanine Roddy, M.A., CCC-SLP — founder/CEO, opened 2016 after relocating from Minnesota.",
    ownershipStatus: "founder_named",
    ownerName: "Jeanine Roddy, CCC-SLP",
    peSignal: "No PE press found. Privately held per LinkedIn.",
    classification: "target_candidate",
    verificationNote: "Four published North DFW sites. Strongest Collin independent in this pass.",
    nextAction: "SOS + payer mix. Rank against Synaptic as the other DFW multi-site founder platform.",
    licenseLookups: [TDLR, ECPTOTE, SOS],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: null,
      members: "Jeanine Roddy, CCC-SLP (Voyage Dallas interview + site). SOS members not pulled.",
      note: "Founder named in a published interview. Texas SOS filing not pulled.",
    }),
    licenseChecks: licensesNotPulled("TDLR", "ECPTOTE"),
    city: "Frisco",
    lat: 33.1507,
    lng: -96.8236,
    outreachRank: 2,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "target",
  },
  {
    id: "synaptic",
    countyName: "Dallas County",
    metroId: "dfw",
    name: "Synaptic Pediatric Therapies",
    legalName: "Synaptic Pediatric Therapies, LLC",
    websiteUrl: "https://synapticpediatrictherapies.com/",
    sourceUrl: "https://synapticpediatrictherapies.com/",
    sources: [
      { label: "Practice site", url: "https://synapticpediatrictherapies.com/" },
      { label: "Dallas Business Journal 2023", url: "https://www.bizjournals.com/dallas/news/2023/03/14/synaptic-pediatric-therapies-mohammad-elashi.html" },
      { label: "Founder profile", url: "https://texasbusiness.org/alumni-spotlight-mohammad-elashi/" },
    ],
    services: ["SLP", "OT"],
    footprint: "Richardson, Wylie, Mesquite, NRH, DeSoto, Irving, Arlington, Garland (Royse City per FINDconnect)",
    locationCount: 8,
    clinicianEstimate: "Not published. 8–9 sites implies a real payroll — get a count on the call.",
    ownershipSignal: "Mohammad Elashi, founder/director. Bootstrapped; he has said no outside investors or debt. Public ambition to be DFW's #1 pediatric provider.",
    ownershipStatus: "founder_named",
    ownerName: "Mohammad Elashi",
    peSignal: "Founder claims bootstrapped. Confirm before treating as unencumbered.",
    classification: "target_candidate",
    verificationNote: "Local consolidator already. Missed by the NPPES name-match extract. Assigned to Dallas as the DFW home; sites cross Dallas, Tarrant, and Collin.",
    nextAction: "Decide partner vs acquire vs compete. Get current site list and payer mix.",
    licenseLookups: [TDLR, ECPTOTE, SOS],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: "Synaptic Pediatric Therapies, LLC",
      members: "Mohammad Elashi (Dallas Business Journal / founder profile). SOS members not pulled.",
      note: "Founder named in press. Bootstrapped claim is his, not a filing. SOS not pulled.",
    }),
    licenseChecks: licensesNotPulled("TDLR", "ECPTOTE"),
    city: "Richardson",
    lat: 32.9483,
    lng: -96.7299,
    outreachRank: 3,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "target",
  },
  {
    id: "pta-sa",
    countyName: "Bexar County",
    metroId: "san-antonio",
    name: "Pediatric Therapy Associates",
    legalName: "S. Potts and Professionals, Inc.",
    websiteUrl: "https://www.pediatrictherapyassoc.com/",
    sourceUrl: "https://www.pediatrictherapyassoc.com/",
    sources: [
      { label: "Practice site", url: "https://www.pediatrictherapyassoc.com/" },
      { label: "Founder write-up", url: "https://cpfamilynetwork.org/resources/resources-guide/pediatric-therapy-associates-san-antonio-tx/" },
    ],
    services: ["SLP", "OT", "PT", "feeding"],
    footprint: "1 San Antonio outpatient site (Village Dr); third expansion of that clinic",
    locationCount: 1,
    clinicianEstimate: "17 therapists / 185+ combined years (CP Family Network profile)",
    ownershipSignal: "Sharrie Potts founded 1997 and is still described as owner. NPI legal name S. Potts and Professionals, Inc.",
    ownershipStatus: "founder_named",
    ownerName: "Sharrie Potts",
    peSignal: "No PE press found.",
    classification: "target_candidate",
    verificationNote: "Cleanest single-clinic SA target: named founder, disclosed therapist count, live site, matching NPI.",
    nextAction: "Founder outreach. Confirm headcount and whether a process has ever been run.",
    licenseLookups: [TDLR, ECPTOTE, SOS],
    sosCheck: sosNamed({
      status: "npi_named",
      legalName: "S. Potts and Professionals, Inc.",
      members: "Sharrie Potts (NPI legal name + founder write-up). SOS members not pulled.",
      note: "Named on NPI and a public profile. Texas SOS filing not pulled.",
    }),
    licenseChecks: licensesNotPulled("TDLR", "ECPTOTE"),
    city: "San Antonio",
    lat: 29.4944,
    lng: -98.551,
    outreachRank: 4,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "target",
  },
  {
    id: "kids-developmental-clinic",
    countyName: "Harris County",
    metroId: "houston",
    name: "Kids Developmental Clinic",
    legalName: "Kids DC, LLC",
    websiteUrl: "https://www.kidsdevelopmentalclinic.com/",
    sourceUrl: "https://www.kidsdevelopmentalclinic.com/clinics/",
    sources: [
      { label: "Four clinic addresses", url: "https://www.kidsdevelopmentalclinic.com/" },
      { label: "NPI 1225076904 — Diana P. Dinn, PT, MBA", url: "https://npiregistry.cms.hhs.gov/" },
    ],
    services: ["SLP", "OT", "PT"],
    footprint: "Southwest, West, North Houston + Pasadena",
    locationCount: 4,
    clinicianEstimate: "LinkedIn ~43 employees / $5–25M — directory estimates only",
    ownershipSignal: "NPI authorized official Diana P. Dinn, PT, MBA (administrator). Older directories list Deanna/Diana Dinn as owner. SOS members not pulled.",
    ownershipStatus: "clinician_owned_named",
    ownerName: "Diana P. Dinn, PT, MBA",
    peSignal: "No PE press found. Also describes home-health operations — confirm entity map.",
    classification: "target_candidate",
    verificationNote: "Four published ORF sites. Not in the NPPES name-match extract. Licensed pediatric outpatient rehab claim on site.",
    nextAction: "SOS on Kids DC, LLC / KDT. Separate ORF vs home-health P&L before a bid.",
    licenseLookups: [ECPTOTE, TDLR, SOS],
    sosCheck: sosNamed({
      status: "npi_named",
      legalName: "Kids DC, LLC",
      members: "Diana P. Dinn, PT, MBA (NPI authorized official). SOS members not pulled.",
      note: "NPI names Dinn as administrator/owner in older directories. SOS not pulled.",
    }),
    licenseChecks: licensesNotPulled("ECPTOTE", "TDLR"),
    city: "Houston",
    lat: 29.7056,
    lng: -95.5383,
    outreachRank: 5,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "target",
  },
  {
    id: "ptc-kids",
    countyName: "Harris County",
    metroId: "houston",
    name: "Pediatric Therapy Center",
    legalName: "113015 Therapy, PLLC",
    websiteUrl: "https://www.ptckids.com/",
    sourceUrl: "https://www.ptckids.com/",
    sources: [
      { label: "Practice site", url: "https://www.ptckids.com/" },
      { label: "Jane Knowlton — founder and co-owner", url: "https://www.ptckids.com/team/jane-knowlton/" },
      { label: "NPI 1033575840 — Jane Knowlton, owner", url: "https://npiregistry.cms.hhs.gov/" },
    ],
    services: ["SLP", "OT", "PT", "feeding"],
    footprint: "1 SW Houston clinic, ~15,000 sq ft (self-reported)",
    locationCount: 1,
    clinicianEstimate: "~40 contracted therapists (practice website — confirm W-2 vs 1099)",
    ownershipSignal: "Jane Knowlton, PT, DPT — site: founder and co-owner; NPI 1033575840 (113015 Therapy, PLLC) lists her as owner. Co-owner still unnamed. A second org NPI (1508067935) names Christina Bednorz — confirm the entity map before a bid.",
    ownershipStatus: "founder_named",
    ownerName: "Jane Knowlton, PT, DPT",
    peSignal: "No PE press found.",
    classification: "target_candidate",
    verificationNote: "Longest-tenured Houston clinic in this set. Contracted-therapist model still changes valuation.",
    nextAction: "SOS on 113015 Therapy, PLLC. Ask who the unnamed co-owner is and how much of the bench is W-2.",
    licenseLookups: [TDLR, ECPTOTE, SOS],
    sosCheck: sosNamed({
      status: "npi_named",
      legalName: "113015 Therapy, PLLC",
      members: "Jane Knowlton, PT, DPT (NPI owner + site founder/co-owner). Co-owner unnamed. SOS not pulled.",
      note: "NPI and team page name Knowlton. Do not treat the Pearland or other PTC brands as this entity.",
    }),
    licenseChecks: licensesNotPulled("TDLR", "ECPTOTE"),
    city: "Houston",
    lat: 29.6894,
    lng: -95.546,
    outreachRank: 6,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "target",
  },
  {
    id: "wishing-well",
    countyName: "Harris County",
    metroId: "houston",
    name: "Wishing Well Pediatric Therapy Center",
    legalName: "MERC Therapy Centers, LLC",
    websiteUrl: "https://wishingwellpediatrics.com/",
    sourceUrl: "https://wishingwellpediatrics.com/locations/",
    sources: [
      { label: "Two Houston addresses", url: "https://wishingwellpediatrics.com/locations/" },
      { label: "NPI 1427328145 — Michele Eglinger, owner", url: "https://npiregistry.cms.hhs.gov/" },
    ],
    services: ["SLP", "OT", "PT"],
    footprint: "Gessner + Greens Parkway; adult rehab co-located",
    locationCount: 2,
    clinicianEstimate: "LinkedIn 4 employees — likely understated vs two clinics",
    ownershipSignal: "Michele Eglinger, owner (NPI authorized official for MERC Therapy Centers, LLC). Therapist-owned per LinkedIn. Founded 2012.",
    ownershipStatus: "founder_named",
    ownerName: "Michele Eglinger",
    peSignal: "No PE press found.",
    classification: "target_candidate",
    verificationNote: "Two pediatric sites plus adult rehab in the same buildings. Medicaid + commercial claimed.",
    nextAction: "SOS on MERC. Ask how much of the P&L is pediatric vs adult.",
    licenseLookups: [ECPTOTE, TDLR, SOS],
    sosCheck: sosNamed({
      status: "npi_named",
      legalName: "MERC Therapy Centers, LLC",
      members: "Michele Eglinger (NPI authorized official / owner). SOS members not pulled.",
      note: "NPI names Eglinger as owner. Texas SOS filing not pulled.",
    }),
    licenseChecks: licensesNotPulled("ECPTOTE", "TDLR"),
    city: "Houston",
    lat: 29.8264,
    lng: -95.5456,
    outreachRank: 8,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "target",
  },
  {
    id: "kidworks",
    countyName: "Travis County",
    metroId: "austin",
    name: "KidWorks Therapy Services",
    legalName: null,
    websiteUrl: "https://kidworkstherapy.com/",
    sourceUrl: "https://kidworkstherapy.com/",
    sources: [{ label: "Practice site (founder named)", url: "https://kidworkstherapy.com/" }],
    services: ["SLP", "OT", "PT"],
    footprint: "1 South-Central Austin house clinic, 3607 Manchaca Rd",
    locationCount: 1,
    clinicianEstimate: "Team page exists; count not scraped in this pass",
    ownershipSignal: "Established 1999 by Rebecca Pokluda. Still presented as her practice.",
    ownershipStatus: "founder_named",
    ownerName: "Rebecca Pokluda",
    peSignal: "No PE press found.",
    classification: "target_candidate",
    verificationNote: "Longest-tenured Austin independent in this pass. Single site, DIR/Floortime.",
    nextAction: "Succession conversation. First Austin call after Cole/NAPA are marked as competitors.",
    licenseLookups: [TDLR, ECPTOTE, SOS],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: null,
      members: "Rebecca Pokluda (practice site). SOS members not pulled.",
      note: "Founder named on the official site. Texas SOS filing not pulled.",
    }),
    licenseChecks: licensesNotPulled("TDLR", "ECPTOTE"),
    city: "Austin",
    lat: 30.2439,
    lng: -97.7889,
    outreachRank: 7,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "target",
  },
  {
    id: "ctoa",
    countyName: "Travis County",
    metroId: "austin",
    name: "Children's Therapeutics of Austin",
    legalName: "CTOA LLC",
    websiteUrl: "http://childrenstherapeutics.com/",
    sourceUrl: "http://childrenstherapeutics.com/about-us/",
    sources: [{ label: "About / Hancock address", url: "http://childrenstherapeutics.com/about-us/" }],
    services: ["SLP", "OT", "PT"],
    footprint: "1 Tarrytown house clinic, 3211 Hancock Dr",
    locationCount: 1,
    clinicianEstimate: "Not published",
    ownershipSignal: "NPI 1851304802 authorized official: Gabriele D. Rose, Manager. BBB lists her as member/PT. Public profile says she retired in 2020. Current SOS members after retirement are not confirmed.",
    ownershipStatus: "clinician_owned_named",
    ownerName: "Gabriele D. Rose (NPI/BBB; retired 2020)",
    peSignal: "No PE press found.",
    classification: "target_candidate",
    verificationNote: "Live site, matching NPI. Tenure is real. Current control after Rose’s 2020 retirement is the hole.",
    nextAction: "SOS on CTOA LLC. Do not assume Rose still owns it.",
    licenseLookups: [TDLR, ECPTOTE, SOS],
    sosCheck: sosNamed({
      status: "npi_named",
      legalName: "CTOA LLC",
      members: "Gabriele D. Rose, Manager (NPI) / Member (BBB). Retired 2020 per public profile. SOS not pulled.",
      note: "NPI and BBB name Rose. That is not a current-member confirmation.",
    }),
    licenseChecks: licensesNotPulled("TDLR", "ECPTOTE"),
    city: "Austin",
    lat: 30.3072,
    lng: -97.7583,
    outreachRank: 11,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "target",
  },
  {
    id: "line-leader",
    countyName: "Travis County",
    metroId: "austin",
    name: "Line Leader Pediatric Therapy",
    legalName: "Line Leader Pediatric Therapy, PLLC",
    websiteUrl: "https://www.lineleadertherapy.com/",
    sourceUrl: "https://www.lineleadertherapy.com/",
    sources: [
      { label: "About / founder", url: "https://www.lineleadertherapy.com/about-us" },
      { label: "Sharon Wisnieski LinkedIn", url: "https://www.linkedin.com/in/sharon-wisnieski-otr-92083417" },
    ],
    services: ["SLP", "OT", "PT", "feeding"],
    footprint: "1 north-central Austin center (2222 & MoPac) + schools/homes",
    locationCount: 1,
    clinicianEstimate: "Not published",
    ownershipSignal: "Sharon Wisnieski, OTR, MS — founder (2009), site president, LinkedIn CEO of Line Leader Pediatric Therapy, PLLC. TOTA speaker bio calls her the owner.",
    ownershipStatus: "founder_named",
    ownerName: "Sharon Wisnieski, OTR",
    peSignal: "No PE press found.",
    classification: "target_candidate",
    verificationNote: "Austin independent with a named OT founder. Single site. SOS still not pulled.",
    nextAction: "SOS on the PLLC. Second Austin call after KidWorks.",
    licenseLookups: [TDLR, ECPTOTE, SOS],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: "Line Leader Pediatric Therapy, PLLC",
      members: "Sharon Wisnieski, OTR (site president + LinkedIn founder/CEO). SOS members not pulled.",
      note: "Named on the official about page and her LinkedIn. Texas SOS filing not pulled.",
    }),
    licenseChecks: licensesNotPulled("ECPTOTE", "TDLR"),
    city: "Austin",
    lat: 30.307,
    lng: -97.741,
    outreachRank: 14,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "verified",
  },
  {
    id: "therapy-spot",
    countyName: "Collin County",
    metroId: "dfw",
    name: "The Therapy Spot",
    legalName: null,
    websiteUrl: "https://www.thetherapyspottx.com/",
    sourceUrl: "https://www.thetherapyspottx.com/index.php",
    sources: [
      { label: "Home", url: "https://www.thetherapyspottx.com/index.php" },
      { label: "Denton", url: "https://www.thetherapyspottx.com/contact-therapy-denton-texas.php" },
      { label: "Wylie", url: "https://www.thetherapyspottx.com/contact-therapy-wylie-texas.php" },
    ],
    services: ["SLP", "OT", "PT"],
    footprint: "Carrollton, Denton, Prosper, Wylie",
    locationCount: 4,
    clinicianEstimate: "Not published",
    ownershipSignal: "Website and LinkedIn company page name no founder. Cody Roche is Director of OT, not an owner. Pearland Therapy Spot PLLC (David Gerke / NPI 1407914872) is a different clinic.",
    ownershipStatus: "independent_unnamed",
    ownerName: null,
    peSignal: "Unknown — do not outreach until SOS attaches a person.",
    classification: "target_candidate",
    verificationNote: "Four DFW sites, shared phone 972-559-4457. Still the ownership hole on the DFW list.",
    nextAction: "SOS first. Do not call a generic intake line.",
    licenseLookups: [TDLR, ECPTOTE, SOS],
    sosCheck: sosNamed({
      status: "not_pulled",
      legalName: null,
      members: null,
      note: "No owner on the DFW site. Do not use the Pearland Therapy Spot PLLC filing. Texas SOS search not completed.",
    }),
    licenseChecks: licensesNotPulled("TDLR", "ECPTOTE"),
    city: "Carrollton",
    lat: 32.9756,
    lng: -96.89,
    outreachRank: 10,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "target",
  },
  {
    id: "anchor-pediatric-therapy",
    countyName: "Tarrant County",
    metroId: "dfw",
    name: "Anchor Pediatric Therapy, LLC",
    legalName: "Anchor Pediatric Therapy, LLC",
    websiteUrl: "https://www.anchortherapytx.com/",
    sourceUrl: "https://www.anchortherapytx.com/contact",
    sources: [
      { label: "Practice site", url: "https://www.anchortherapytx.com/" },
      { label: "TCU founder story", url: "https://harriscollege.tcu.edu/stories/2024/frogpreneurruelas.php" },
    ],
    services: ["SLP", "OT", "feeding"],
    footprint: "2 Fort Worth clinics (I-35/121 and S. Hulen / I-20)",
    locationCount: 2,
    clinicianEstimate: "LinkedIn 7 employees (down YoY) — treat as small",
    ownershipSignal: "Kenneth and Meghan Ruelas co-founded 2012. Kenneth is CEO/owner on NPI. Bilingual. TCU EMBA 2022.",
    ownershipStatus: "founder_named",
    ownerName: "Kenneth and Meghan Ruelas",
    peSignal: "No PE press found. Still described as a founder couple.",
    classification: "target_candidate",
    verificationNote: "Named owners, two sites, no PT. Real add-on, not a platform.",
    nextAction: "Call Ruelas. Confirm site addresses and whether they want capital or a sale.",
    licenseLookups: [TDLR, ECPTOTE, SOS],
    sosCheck: sosNamed({
      status: "npi_named",
      legalName: "Anchor Pediatric Therapy, LLC",
      members: "Kenneth and Meghan Ruelas (site + TCU story; Kenneth CEO/owner on NPI). SOS not pulled.",
      note: "Named founder couple on the site and NPI. Texas SOS filing not pulled.",
    }),
    licenseChecks: licensesNotPulled("TDLR", "ECPTOTE"),
    city: "Fort Worth",
    lat: 32.7555,
    lng: -97.3308,
    outreachRank: 9,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "target",
  },
  {
    id: "cowtown-pediatrix",
    countyName: "Tarrant County",
    metroId: "dfw",
    name: "Cowtown Pediatrix Clinic, LLC",
    legalName: "Cowtown Pediatrix Clinic, LLC",
    websiteUrl: "https://cowtownpediatrixclinic.com/",
    sourceUrl: "https://cowtownpediatrixclinic.com/about/",
    sources: [
      { label: "Founder page", url: "https://cowtownpediatrixclinic.com/about/" },
      { label: "Legal name / address", url: "https://cowtownpediatrixclinic.com/terms-of-service/" },
    ],
    services: ["SLP", "OT", "feeding"],
    footprint: "1 Fort Worth clinic, 4011 Benbrook Hwy Suite B",
    locationCount: 1,
    clinicianEstimate: "LinkedIn 2–10; founder still treats. Small.",
    ownershipSignal: "Sue Khammar, OTR — founder/CEO since 2013. Goldman Sachs 10KSB Class of 2025. Woman-owned.",
    ownershipStatus: "founder_named",
    ownerName: "Sue Khammar, OTR",
    peSignal: "No PE press found. 10KSB is a training program, not capital.",
    classification: "target_candidate",
    verificationNote: "Named founder, one site, OT/SLP. Tuck-in, not a platform.",
    nextAction: "Only after Therapedia and Anchor. Confirm she wants a conversation.",
    licenseLookups: [ECPTOTE, TDLR, SOS],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: "Cowtown Pediatrix Clinic, LLC",
      members: "Sue Khammar, OTR (site founder/CEO). SOS members not pulled.",
      note: "Named on the about page. Texas SOS filing not pulled.",
    }),
    licenseChecks: licensesNotPulled("ECPTOTE", "TDLR"),
    city: "Fort Worth",
    lat: 32.725,
    lng: -97.378,
    outreachRank: 12,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "target",
  },
  {
    id: "jump-start",
    countyName: "Tarrant County",
    metroId: "dfw",
    name: "Jump Start Pediatric Therapy Center, LLC",
    legalName: "Jump Start Pediatric Therapy Center, LLC",
    websiteUrl: "https://www.jumpstartcenter.com/",
    sourceUrl: "https://www.jumpstartcenter.com/",
    sources: [
      { label: "Founder bio", url: "https://www.jumpstartcenter.com/lauren-roe" },
      { label: "Origin story", url: "https://www.jumpstartcenter.com/post/the-beginning" },
    ],
    services: ["SLP"],
    footprint: "1 North Fort Worth clinic, 7500 N Beach St",
    locationCount: 1,
    clinicianEstimate: "Site history: 7 therapists, 2,700 sq ft (older post)",
    ownershipSignal: "Lauren Roe, MS CCC-SLP, owner/COO on NPI. Husband Wesley Roe joined 2011 for ops. Opened 2009.",
    ownershipStatus: "founder_named",
    ownerName: "Lauren and Wesley Roe",
    peSignal: "No PE press found.",
    classification: "target_candidate",
    verificationNote: "SLP-only. Useful Fort Worth proof-point; weaker as a platform seed than Therapedia.",
    nextAction: "Tuck-in only if building a North Fort Worth SLP cluster.",
    licenseLookups: [TDLR, SOS],
    sosCheck: sosNamed({
      status: "npi_named",
      legalName: "Jump Start Pediatric Therapy Center, LLC",
      members: "Lauren Roe, CCC-SLP (site + NPI owner/COO); Wesley Roe (ops). SOS not pulled.",
      note: "Named on the founder bio. Texas SOS filing not pulled.",
    }),
    licenseChecks: licensesNotPulled("TDLR"),
    city: "Fort Worth",
    lat: 32.862,
    lng: -97.29,
    outreachRank: 13,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "target",
  },
  {
    id: "pediatric-therapy-specialists",
    countyName: "Bexar County",
    metroId: "san-antonio",
    name: "Pediatric Therapy Specialists",
    legalName: "Pediatric Therapy Specialists, LLC",
    websiteUrl: "https://pedts.com/",
    sourceUrl: "https://pedts.com/about-us",
    sources: [{ label: "About / owners named", url: "https://pedts.com/about-us" }],
    services: ["SLP", "OT", "PT"],
    footprint: "San Antonio + Schertz",
    locationCount: 2,
    clinicianEstimate: "25 therapists (practice about page)",
    ownershipSignal: "Elizabeth Dinn Marsh, OTR, and Eric Adams, BBA — owners named on pedts.com/about-us. Unrelated: Marcy Goble’s Pediatric Therapy Specialists, Inc. is a different entity.",
    ownershipStatus: "founder_named",
    ownerName: "Elizabeth Dinn Marsh, OTR and Eric Adams",
    peSignal: "No PE press found.",
    classification: "target_candidate",
    verificationNote: "Two sites, disclosed therapist bench, named owners. Second SA independent after PTA.",
    nextAction: "SOS on Pediatric Therapy Specialists, LLC. Compare to PTA (Potts) before stacking SA outreach.",
    licenseLookups: [TDLR, ECPTOTE, SOS],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: "Pediatric Therapy Specialists, LLC",
      members: "Elizabeth Dinn Marsh, OTR and Eric Adams (about page). SOS members not pulled.",
      note: "Named on the official about page. Do not confuse with Marcy Goble’s Inc.",
    }),
    licenseChecks: licensesNotPulled("ECPTOTE", "TDLR"),
    city: "San Antonio",
    lat: 29.55,
    lng: -98.61,
    outreachRank: 15,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "verified",
  },
  {
    id: "kidspeak",
    countyName: "Dallas County",
    metroId: "dfw",
    name: "KidSpeak",
    legalName: "KidSpeak, LLC",
    websiteUrl: "https://www.kidspeakdallas.com/",
    sourceUrl: "https://www.kidspeakdallas.com/payment-options",
    sources: [{ label: "OON / cash-pay policy", url: "https://www.kidspeakdallas.com/payment-options" }],
    services: ["SLP"],
    footprint: "1 Addison office, 4530 Beltway Dr",
    locationCount: 1,
    clinicianEstimate: "Small private-practice team; cash-pay",
    ownershipSignal: "Amanda Rollins, co-owner & SLP (NPI). Opened 2008.",
    ownershipStatus: "founder_named",
    ownerName: "Amanda Rollins",
    peSignal: "No PE. Cash-pay boutique.",
    classification: "verified_operator",
    verificationNote: "Real Dallas clinic. Not a platform target on current evidence.",
    nextAction: "Leave on the map. Do not prioritize.",
    licenseLookups: [TDLR, SOS],
    sosCheck: sosNamed({
      status: "npi_named",
      legalName: "KidSpeak, LLC",
      members: "Amanda Rollins (NPI co-owner). SOS members not pulled.",
      note: "Named on NPI. Boutique cash-pay. Texas SOS filing not pulled.",
    }),
    licenseChecks: licensesNotPulled("TDLR"),
    city: "Addison",
    lat: 32.9618,
    lng: -96.8292,
    outreachRank: null,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "verified",
  },
  {
    id: "speech-wings",
    countyName: "Dallas County",
    metroId: "dfw",
    name: "Speech Wings Therapy",
    legalName: "Speech Wings Therapy, LLC",
    websiteUrl: "https://speechwingstherapy.com/",
    sourceUrl: "https://speechwingstherapy.com/about-us/",
    sources: [{ label: "About — Courtney Willis, founder/CEO", url: "https://speechwingstherapy.com/about-us/" }],
    services: ["SLP"],
    footprint: "1 North Dallas office, 11551 Forest Central Dr #212",
    locationCount: 1,
    clinicianEstimate: "Small clinician team on the about page",
    ownershipSignal: "Courtney Willis, MS, CCC-SLP — founded the practice and is CEO/clinical director on the official about page. Facebook lists Speech Wings Therapy, LLC.",
    ownershipStatus: "founder_named",
    ownerName: "Courtney Willis, CCC-SLP",
    peSignal: "No PE press found.",
    classification: "verified_operator",
    verificationNote: "Named Dallas boutique. Not a platform target on current evidence.",
    nextAction: "Leave on the map. SOS only if ranking boutique SLP add-ons.",
    licenseLookups: [TDLR, SOS],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: "Speech Wings Therapy, LLC",
      members: "Courtney Willis, CCC-SLP (about page founder/CEO). SOS members not pulled.",
      note: "Named on the official about page. Texas SOS filing not pulled.",
    }),
    licenseChecks: licensesNotPulled("TDLR"),
    city: "Dallas",
    lat: 32.91,
    lng: -96.751,
    outreachRank: null,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "verified",
  },
  {
    id: "therapy-at-the-zone",
    countyName: "Harris County",
    metroId: "houston",
    name: "Therapy At The Zone",
    legalName: null,
    websiteUrl: "https://www.therapyatthezone.com/",
    sourceUrl: "https://www.therapyatthezone.com/",
    sources: [{ label: "Team page", url: "https://www.therapyatthezone.com/meetourteam" }],
    services: ["SLP", "OT", "PT"],
    footprint: "1 clinic inside The Zone Sports Complex, 10371 Stella Link",
    locationCount: 1,
    clinicianEstimate: "Several named independent therapists on the team page",
    ownershipSignal: "Site: 'the team is comprised of independent therapists.' Not a single P&L.",
    ownershipStatus: "independent_unnamed",
    ownerName: null,
    peSignal: "n/a — structure is the issue, not PE",
    classification: "verified_operator",
    verificationNote: "Operating clinic. Hard to buy as one company. See rejected log.",
    nextAction: "Do not outreach as an acquisition. Confirm if any therapist wants to sell a book.",
    licenseLookups: [TDLR, ECPTOTE],
    sosCheck: sosNamed({
      status: "not_found",
      legalName: null,
      members: null,
      note: "Site describes independent therapists sharing a floor. Not one SOS target.",
    }),
    licenseChecks: licensesNotPulled("TDLR", "ECPTOTE"),
    city: "Houston",
    lat: 29.67,
    lng: -95.429,
    outreachRank: null,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "passed",
  },
  {
    id: "cole-houston",
    countyName: "Harris County",
    metroId: "houston",
    name: "Cole Pediatric Therapy",
    legalName: "Cole Health, Inc.",
    websiteUrl: "https://www.colehealth.com/",
    sourceUrl: "https://www.colehealth.com/contact/",
    sources: [
      { label: "Founders", url: "https://www.colehealth.com/about/" },
      { label: "Location list", url: "https://www.colehealth.com/contact/" },
    ],
    services: ["SLP", "OT", "PT", "ABA"],
    footprint: "10 Greater Houston sites; 24 company-wide",
    locationCount: 10,
    clinicianEstimate: "LinkedIn ~174–289 / ~$30M — directory estimates. Woodlands Online: 350 employees at 20-year mark.",
    ownershipSignal: "Jennifer Cole, MS CCC-SLP and Adam Cole, MBA, co-founders (2001). Clinician-owned, multi-state. Name has no pediatric token — NPPES name-match missed the chain.",
    ownershipStatus: "platform_scaled",
    ownerName: "Jennifer and Adam Cole",
    peSignal: "No PE sponsor found on the public site. Still a platform, not an add-on.",
    classification: "competitor_benchmark",
    verificationNote: "Houston incumbent. Use as the competitor set.",
    nextAction: "Do not put in the outreach queue as a target.",
    licenseLookups: [TDLR, ECPTOTE],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: "Cole Health, Inc.",
      members: "Jennifer Cole, CCC-SLP and Adam Cole (about page). SOS not pulled.",
      note: "Platform, not an add-on. SOS not required to pass.",
    }),
    licenseChecks: licensesNotPulled("TDLR", "ECPTOTE"),
    city: "Houston",
    lat: 30.158,
    lng: -95.461,
    outreachRank: null,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "passed",
  },
  {
    id: "cole-san-antonio",
    countyName: "Bexar County",
    metroId: "san-antonio",
    name: "Cole Pediatric Therapy",
    legalName: "Cole Health, Inc.",
    websiteUrl: "https://www.colehealth.com/",
    sourceUrl: "https://www.colehealth.com/contact/",
    sources: [{ label: "Stone Oak / South SA / Schertz", url: "https://www.colehealth.com/contact/" }],
    services: ["SLP", "OT", "PT", "ABA"],
    footprint: "Stone Oak, South San Antonio, Schertz",
    locationCount: 3,
    clinicianEstimate: "See Cole Houston record for company-level size",
    ownershipSignal: "Same Cole Health platform.",
    ownershipStatus: "platform_scaled",
    ownerName: "Jennifer and Adam Cole",
    peSignal: "No PE sponsor found.",
    classification: "competitor_benchmark",
    verificationNote: "SA competitor, not a target.",
    nextAction: "Benchmark only.",
    licenseLookups: [TDLR, ECPTOTE],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: "Cole Health, Inc.",
      members: "Jennifer and Adam Cole. Same platform as Houston.",
      note: "Benchmark only.",
    }),
    licenseChecks: licensesNotPulled("TDLR", "ECPTOTE"),
    city: "San Antonio",
    lat: 29.608,
    lng: -98.478,
    outreachRank: null,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "passed",
  },
  {
    id: "cole-austin",
    countyName: "Travis County",
    metroId: "austin",
    name: "Cole Pediatric Therapy",
    legalName: "Cole Health, Inc.",
    websiteUrl: "https://www.colehealth.com/",
    sourceUrl: "https://www.colehealth.com/contact/",
    sources: [{ label: "North + South Austin", url: "https://www.colehealth.com/contact/" }],
    services: ["SLP", "OT", "PT", "ABA"],
    footprint: "North Austin (Hymeadow) + South Austin (S 2nd)",
    locationCount: 2,
    clinicianEstimate: "Company-level — see Cole Houston",
    ownershipSignal: "Same Cole Health platform.",
    ownershipStatus: "platform_scaled",
    ownerName: "Jennifer and Adam Cole",
    peSignal: "No PE sponsor found.",
    classification: "competitor_benchmark",
    verificationNote: "Austin already has a scaled local platform.",
    nextAction: "Benchmark only.",
    licenseLookups: [TDLR, ECPTOTE],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: "Cole Health, Inc.",
      members: "Jennifer and Adam Cole. Same platform.",
      note: "Benchmark only.",
    }),
    licenseChecks: licensesNotPulled("TDLR", "ECPTOTE"),
    city: "Austin",
    lat: 30.4,
    lng: -97.75,
    outreachRank: null,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "passed",
  },
  {
    id: "cole-frisco",
    countyName: "Collin County",
    metroId: "dfw",
    name: "Cole Pediatric Therapy",
    legalName: "Cole Health, Inc.",
    websiteUrl: "https://www.colehealth.com/",
    sourceUrl: "https://www.colehealth.com/contact/",
    sources: [{ label: "Frisco address", url: "https://www.colehealth.com/contact/" }],
    services: ["SLP", "OT", "PT", "ABA"],
    footprint: "5575 Warren Pkwy Ste 106, Frisco",
    locationCount: 1,
    clinicianEstimate: "Company-level — see Cole Houston",
    ownershipSignal: "Same Cole Health platform.",
    ownershipStatus: "platform_scaled",
    ownerName: "Jennifer and Adam Cole",
    peSignal: "No PE sponsor found.",
    classification: "competitor_benchmark",
    verificationNote: "Cole's North DFW flag.",
    nextAction: "Benchmark only.",
    licenseLookups: [TDLR, ECPTOTE],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: "Cole Health, Inc.",
      members: "Jennifer and Adam Cole. Same platform.",
      note: "Benchmark only.",
    }),
    licenseChecks: licensesNotPulled("TDLR", "ECPTOTE"),
    city: "Frisco",
    lat: 33.1507,
    lng: -96.8236,
    outreachRank: null,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "passed",
  },
  {
    id: "napa-austin",
    countyName: "Travis County",
    metroId: "austin",
    name: "NAPA Center Austin",
    legalName: "NAPA Center",
    websiteUrl: "https://napacenter.org/locations/napa-center-austin/",
    sourceUrl: "https://napacenter.org/locations/napa-center-austin/",
    sources: [{ label: "Austin location", url: "https://napacenter.org/locations/napa-center-austin/" }],
    services: ["SLP", "OT", "PT", "feeding"],
    footprint: "7801 N Lamar Blvd Ste A114",
    locationCount: 1,
    clinicianEstimate: "National intensive brand — local headcount not the point",
    ownershipSignal: "Founded 2008 by Lynette LaScala. Multi-city intensive-therapy company.",
    ownershipStatus: "platform_scaled",
    ownerName: "Lynette LaScala (founder)",
    peSignal: "National brand. Not a Texas independent.",
    classification: "competitor_benchmark",
    verificationNote: "Different economics (3-week IMOT). See rejected log.",
    nextAction: "Pass as a target.",
    licenseLookups: [TDLR, ECPTOTE],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: "NAPA Center",
      members: "Lynette LaScala (founder). National brand.",
      note: "Not a Texas independent. SOS not relevant.",
    }),
    licenseChecks: licensesNotPulled("TDLR", "ECPTOTE"),
    city: "Austin",
    lat: 30.348,
    lng: -97.712,
    outreachRank: null,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "passed",
  },
  {
    id: "brighton-center",
    countyName: "Bexar County",
    metroId: "san-antonio",
    name: "Brighton Center",
    legalName: null,
    websiteUrl: "https://brightonsa.org/",
    sourceUrl: "https://brightonsa.org/south-texas-pediatric-therapy-services-3-6/",
    sources: [{ label: "Therapy services page", url: "https://brightonsa.org/south-texas-pediatric-therapy-services-3-6/" }],
    services: ["SLP", "OT", "PT"],
    footprint: "3 San Antonio campus addresses",
    locationCount: 3,
    clinicianEstimate: "Nonprofit staff — not a deal size signal",
    ownershipSignal: "Nonprofit.",
    ownershipStatus: "nonprofit",
    ownerName: null,
    peSignal: "n/a",
    classification: "competitor_benchmark",
    verificationNote: "Verified participant, not an acquisition lead.",
    nextAction: "Pass.",
    licenseLookups: [],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: null,
      members: null,
      note: "Nonprofit. Not an SOS acquisition target.",
    }),
    licenseChecks: [],
    city: "San Antonio",
    lat: 29.425,
    lng: -98.494,
    outreachRank: null,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "passed",
  },
  {
    id: "healthlink-pediatric-clinic",
    countyName: "Bexar County",
    metroId: "san-antonio",
    name: "Healthlink Pediatric Clinic",
    legalName: "Baptist Health System",
    websiteUrl: "https://www.baptisthealthsystem.com/locations/detail/healthlink-pediatric-clinic?c=BBHHP",
    sourceUrl: "https://www.baptisthealthsystem.com/locations/detail/healthlink-pediatric-clinic?c=BBHHP",
    sources: [{ label: "Baptist location page", url: "https://www.baptisthealthsystem.com/locations/detail/healthlink-pediatric-clinic?c=BBHHP" }],
    services: ["SLP", "OT", "PT"],
    footprint: "1 Baptist Health System clinic",
    locationCount: 1,
    clinicianEstimate: "Hospital department",
    ownershipSignal: "Baptist Health System.",
    ownershipStatus: "hospital_system",
    ownerName: null,
    peSignal: "n/a",
    classification: "competitor_benchmark",
    verificationNote: "Hospital clinic. Not a target.",
    nextAction: "Pass.",
    licenseLookups: [],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: "Baptist Health System",
      members: null,
      note: "Hospital department. Not an SOS target.",
    }),
    licenseChecks: [],
    city: "San Antonio",
    lat: 29.425,
    lng: -98.494,
    outreachRank: null,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "passed",
  },
  {
    id: "oaklin-lane",
    countyName: "Dallas County",
    metroId: "dfw",
    name: "Oaklin Lane",
    legalName: null,
    websiteUrl: "https://www.oaklinlane.com/",
    sourceUrl: "https://www.oaklinlane.com/",
    sources: [{ label: "Lake Highlands + Rockwall", url: "https://www.oaklinlane.com/" }],
    services: ["SLP", "OT", "PT", "feeding"],
    footprint: "Lake Highlands (Dallas) + Rockwall",
    locationCount: 2,
    clinicianEstimate: "Not used as a target size signal",
    ownershipSignal: "The sponsor's own clinic brand. Lake Highlands 8610 Greenville Ave #200; Rockwall 789 Justin Rd.",
    ownershipStatus: "sponsor_platform",
    ownerName: null,
    peSignal: "This is the house platform.",
    classification: "competitor_benchmark",
    verificationNote: "On the map so DFW supply is honest. Not a target — it is the buyer.",
    nextAction: "Pass. Use as the platform these add-ons would sit next to.",
    licenseLookups: [],
    sosCheck: sosNamed({
      status: "site_named",
      legalName: null,
      members: null,
      note: "Buyer, not a target.",
    }),
    licenseChecks: [],
    city: "Dallas",
    lat: 32.87,
    lng: -96.73,
    outreachRank: null,
    verifiedAt: "2026-09-01",
    defaultWorkflow: "passed",
  },
];

export const REJECTED_RECORDS: RejectedRecord[] = [
  {
    id: "rej-cole",
    name: "Cole Health / Cole Pediatric Therapy",
    market: "Houston, Austin, San Antonio, Frisco",
    category: "scaled_platform",
    reason: "Founder-owned multi-state platform (24 sites). Competitor set, not an add-on. Legal name has no pediatric token — the NPPES name-match missed the entire chain.",
    sourceUrl: "https://www.colehealth.com/about/",
  },
  {
    id: "rej-napa",
    name: "NAPA Center Austin",
    market: "Travis County",
    category: "scaled_platform",
    reason: "National intensive-therapy brand (IMOT). Different economics than a weekly community clinic.",
    sourceUrl: "https://napacenter.org/locations/napa-center-austin/",
  },
  {
    id: "rej-oaklin",
    name: "Oaklin Lane clinics",
    market: "Dallas / Rockwall",
    category: "sponsor_own_clinics",
    reason: "The house platform (Lake Highlands + Rockwall). On the map for honesty. Not a sourcing target.",
    sourceUrl: "https://www.oaklinlane.com/",
  },
  {
    id: "rej-brighton",
    name: "Brighton Center",
    market: "Bexar County",
    category: "nonprofit",
    reason: "Nonprofit pediatric therapy participant. Not a conventional acquisition.",
    sourceUrl: "https://brightonsa.org/",
  },
  {
    id: "rej-healthlink",
    name: "Healthlink Pediatric Clinic",
    market: "Bexar County",
    category: "hospital",
    reason: "Baptist Health System department.",
    sourceUrl: "https://www.baptisthealthsystem.com/locations/detail/healthlink-pediatric-clinic?c=BBHHP",
  },
  {
    id: "rej-kidsensations",
    name: "KidSensations",
    market: "Travis County",
    category: "closed",
    reason: "Official site: closed May 2025 after 18 years. Still in NPPES. Do not count as supply.",
    sourceUrl: "https://kidsensations.com/",
  },
  {
    id: "rej-zone",
    name: "Therapy At The Zone",
    market: "Harris County",
    category: "not_acquireable_entity",
    reason: "Site says independent therapists sharing a sports-complex floor. Not one acquireable P&L.",
    sourceUrl: "https://www.therapyatthezone.com/",
  },
  {
    id: "rej-t2000",
    name: "Therapy 2000 / Circle of Care",
    market: "Statewide",
    category: "home_health",
    reason: "Pediatric home health (Aveanna-related). Different asset class than clinic roll-up.",
    sourceUrl: "https://www.t2000.com/",
  },
  {
    id: "rej-andrews",
    name: "Children's Health Andrews Institute",
    market: "Denton / Frisco",
    category: "hospital",
    reason: "Hospital sports-medicine site pulled into the NPPES name-match. Not a clinic target.",
  },
  {
    id: "rej-gi",
    name: "Pediatric GI of El Paso",
    market: "Outside shortlist",
    category: "not_a_clinic",
    reason: "Gastroenterology practice with an SLP taxonomy. Exhibit of NPPES noise.",
  },
  {
    id: "rej-therapy-spot-pearland",
    name: "Therapy Spot PLLC (Pearland)",
    market: "Houston Metro",
    category: "not_a_clinic",
    reason:
      "David Gerke / NPI 1407914872. A different clinic from the DFW Therapy Spot four-site brand (thetherapyspottx.com). Do not attach this filing to the Collin/Denton target.",
    sourceUrl: "https://npiregistry.cms.hhs.gov/",
  },
  {
    id: "rej-pts-goble",
    name: "Pediatric Therapy Specialists, Inc. (Marcy Goble)",
    market: "Outside shortlist",
    category: "not_a_clinic",
    reason:
      "Different legal entity from pedts.com (Elizabeth Dinn Marsh and Eric Adams). Do not merge the filings.",
  },
];

export const SOS_STATUS_LABELS: Record<SosCheck["status"], string> = {
  sos_named: "SOS names members",
  npi_named: "NPI names an official",
  site_named: "Site names an owner",
  not_pulled: "SOS filing not pulled",
  not_found: "No acquireable entity found",
};

export const LICENSE_STATUS_LABELS: Record<LicenseCheck["status"], string> = {
  found: "Found",
  not_found: "Not found",
  not_pulled: "Not pulled",
};
